[tox]
envlist =
    py{312,313,314}-django60,

[gh-actions]
python =
    3.12: py312
    3.13: py313
    3.14: py314

[testenv]
passenv = GITHUB_WORKFLOW
commands = python manage.py test
deps =
    psycopg2-binary
    # Django 6.0 (Python 3.12+)
    django60: django>=6.0
