[tox]
envlist =
    py{310,311,312,313}-django42,
    py{310,311,312,313}-django52,

[testenv]
passenv = GITHUB_WORKFLOW
commands = python manage.py test
deps =
    psycopg2-binary
    django42: django~=4.2.0
    django52: django~=5.2.0
