[tox]
envlist =
    py{310,311,312,313}-django60,

[gh-actions]
python =
    3.10: py310
    3.11: py311
    3.12: py312
    3.13: py313

[testenv]
passenv = GITHUB_WORKFLOW
commands = python manage.py test
deps =
    psycopg2-binary
    # Django 6.0 (Python 3.10+)
    django60: django>=6.0
